apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    uid: timescaledb
    url: timescaledb:5432
    user: weather
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      database: weather
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
